# Lightweight Fine-Tuning Project

TODO: In this cell, describe your choices for each of the following

* PEFT technique: LORA
* Model: answerdotai/ModernBERT-base
* Evaluation approach: accuracy
* Fine-tuning dataset: google-research-datasets/go_emotions

In [37]:
# https://medium.com/@mb20261/nlp-by-examples-text-classifications-with-transformers-fc2c14078208

import numpy as np
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {"accuracy": (predictions == labels).mean()}

## Loading and Evaluating a Foundation Model

TODO: In the cells below, load your chosen pre-trained Hugging Face model and evaluate its performance prior to fine-tuning. This step includes loading an appropriate tokenizer and dataset.

In [54]:
from datasets import load_dataset
# dataset = load_dataset("google-research-datasets/go_emotions") 
# dataset = load_dataset("imdb") 


dataset = load_dataset("financial_phrasebank", "sentences_allagree")
dataset = dataset["train"].train_test_split(test_size=0.1)
dataset["validation"] = dataset["test"]
del dataset["test"]

dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label'],
        num_rows: 2037
    })
    validation: Dataset({
        features: ['sentence', 'label'],
        num_rows: 227
    })
})

In [ ]:
from transformers import (AutoTokenizer
                          , AutoModelForSequenceClassification
                          , BertForSequenceClassification
                          , Trainer
                          , TrainingArguments
)
from transformers import default_data_collator, get_linear_schedule_with_warmup
from transformers import AutoModelForSeq2SeqLM
from peft import get_peft_config, get_peft_model, LoraConfig, TaskType

# model_name_or_path = 'bert-base-uncased'
# model_name_or_path = 'answerdotai/ModernBERT-base'
model_name_or_path = "bigscience/mt0-large"
model_name_or_path ='google-bert/bert-base-uncased'
# model_name_or_path ='google-bert/bert-large-uncased'

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name_or_path
    # , num_labels=len(dataset["train"].features["label"].names)
    # ,id2label={0: "negative", 1: "neutral", 2: "positive"}
    # ,label2id={"negative": 0, "neutral": 1, "positive" : 2}
    )
dataset["train"].features["label"].names

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['negative', 'neutral', 'positive']

In [57]:
model.classifier

Linear(in_features=768, out_features=2, bias=True)

In [80]:
from torch import nn 
model.classifier = nn.Linear(768, 3)
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): lora.Linear(
                (base_layer): Linear(in_features=768, out_features=768, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=768, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=768, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): lora.Linear(
                (base_layer): Linear(in_features=768, out_features=768, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=768, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=768, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [81]:
from transformers import AdamW
from transformers import default_data_collator, get_linear_schedule_with_warmup

import torch 
from torch.utils.data import DataLoader
device='mps'
learning_rate = 2e-5
batch_size = 18
num_epochs = 6

In [102]:
# tokenizer(dataset['train']['text'], padding='max_length', truncation=True)
from transformers import default_data_collator, get_linear_schedule_with_warmup
from transformers import AutoModelForSeq2SeqLM
from peft import get_peft_config, get_peft_model, LoraConfig, TaskType
classes = dataset["train"].features["label"].names



def preprocess_function(examples):
    inputs = examples['sentence']
    targets = examples['label']
    model_inputs = tokenizer(
        inputs, 
        padding="max_length", 
        max_length=256, 
        truncation=True,
        return_tensors="pt"
    )
    model_inputs["labels"] = targets
    return model_inputs

In [92]:

preprocessed_datasets = dataset.map(preprocess_function, batched=True, batch_size=batch_size)

from torch.utils.data import default_collate
preprocessed_datasets['train'][0]
train_dataloader = DataLoader(preprocessed_datasets['train'], shuffle=True, collate_fn=default_data_collator
            ,batch_size=batch_size)
eval_dataloader = DataLoader(preprocessed_datasets['validation'], shuffle=True, collate_fn=default_data_collator
            ,batch_size=batch_size)

In [93]:
preprocessed_datasets['train']

print("Unique labels: ", len(set(preprocessed_datasets['train']['labels'])))
eval_dataloader.batch_size, train_dataloader.batch_size

Unique labels:  3

(18, 18)

In [94]:
from transformers import AutoModelForSeq2SeqLM
from peft import get_peft_config, get_peft_model, LoraConfig, TaskType

# tokenizer_name_or_path = "bigscience/mt0-large"

peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS, r=32, lora_dropout=0.1
    , target_modules=['query','value']
    # ,modules_to_save=['classification_head']
)

lora_model = get_peft_model(model, peft_config)
# Load your LoRA weights
from torch import nn
# lora_model.classifier = nn.Linear(768, 3)  
lora_model.print_trainable_parameters()

trainable params: 1,181,955 || all params: 110,666,502 || trainable%: 1.0680

In [95]:
lora_model

model.parameters

<bound method Module.parameters of BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): lora.Linear(
                (base_layer): Linear(in_features=768, out_features=768, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=768, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=768, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): lora.Linear(
                (base_layer): Linear(in_features=768, out_features=768, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=768, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=768, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): ModulesToSaveWrapper(
    (original_module): Linear(in_features=768, out_features=3, bias=True)
    (modules_to_save): ModuleDict(
      (default): Linear(in_features=768, out_features=3, bias=True)
    )
  )
)>

In [96]:
optimizer = AdamW(lora_model.parameters(), lr=learning_rate)

In [97]:
# a = [x for x in train_dataloader]

# len(a[0]['labels'])


# len(batch['labels'])

In [98]:
lora_model

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): BertForSequenceClassification(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30522, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=32, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=32, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=32, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=32, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (activation): Tanh()
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=3, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=3, bias=True)
        )
      )
    )
  )
)

In [99]:
# training and evaluation
from tqdm import tqdm
lora_model = lora_model.to(device)

for epoch in range(num_epochs):
    lora_model.train()
    total_loss = 0
    for step, batch in enumerate(tqdm(train_dataloader)):
        # print(batch)
        batch = {k: v.to(device) for k, v in batch.items()}
        # print("Length INput: ", len(batch['input_ids']))
        outputs = lora_model(**batch)
        loss = outputs.loss
        total_loss += loss.detach().float()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

    lora_model.eval()
    eval_loss = 0
    eval_preds = []
    for step, batch in enumerate(tqdm(eval_dataloader)):
        batch = {k: v.to(device) for k, v in batch.items()}
        with torch.no_grad():
            outputs = lora_model(**batch)
        loss = outputs.loss
        eval_loss += loss.detach().float()
        eval_preds.extend(
            torch.argmax(outputs.logits, -1).detach().cpu().numpy()
        )

    eval_epoch_loss = eval_loss / len(eval_dataloader)
    eval_ppl = torch.exp(eval_epoch_loss)
    train_epoch_loss = total_loss / len(train_dataloader)
    train_ppl = torch.exp(train_epoch_loss)
    print(f"{epoch=}: {train_ppl=} {train_epoch_loss=} {eval_ppl=} {eval_epoch_loss=}")

  0%|          | 0/114 [00:00<?, ?it/s]

ValueError: Expected input batch_size (27) to match target batch_size (18).

In [100]:
File ~/Projects/Udacity GenAI/udacity_genai/.venv/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py:1064, in BertModel.forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
from transformers.models.bert import modeling_bert

SyntaxError: invalid syntax (2320206774.py, line 1)

In [101]:
training_args = TrainingArguments(
    output_dir="bert_peft_trainer"
    , overwrite_output_dir = True
    , do_train=True, do_eval=True
    , eval_strategy = 'epoch'
    , logging_strategy = 'epoch'
    , per_device_eval_batch_size= batch_size
    , per_device_train_batch_size= batch_size
    , learning_rate = learning_rate 
    , optim='adamw_torch'
    , num_train_epochs = num_epochs
    )
bert_peft_trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=preprocessed_datasets['train'], # training dataset requires column input_ids
    eval_dataset=preprocessed_datasets['validation'],
    compute_metrics=compute_metrics,
)
bert_peft_trainer.train()

ValueError: Expected input batch_size (27) to match target batch_size (18).

In [162]:
bert_peft_trainer.model.save_pretrained("bert-peft")

In [147]:
lora_model.save_pretrained('./lora_pretrained')

In [163]:
lora_model.config._name_or_pathx

# Before training
print("Base model num_labels:", model.config.num_labels)
print("LoRA model num_labels:", lora_model.config.num_labels)

# # After loading the merged model
# print("Merged model num_labels:", merged_model.config.num_labels)

AttributeError: 'BertConfig' object has no attribute '_name_or_pathx'

In [164]:
from peft import PeftModel
original_model = AutoModelForSequenceClassification.from_pretrained(
  lora_model.config._name_or_path
)

original_with_adapter = PeftModel.from_pretrained(
  original_model, "bert-peft" # bert-peft; the folder of the saved adapter
)
merged_model = original_with_adapter.merge_and_unload()
merged_model.save_pretrained("merged-model")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [165]:
merged_model.to(device)
merged_model(**tokenized_val)

SequenceClassifierOutput(loss=None, logits=tensor([[-1.0716,  1.0649],
        [-0.9027,  0.9678],
        [-0.9796,  0.9547],
        [-0.7917,  0.8193],
        [-0.9592,  1.0755],
        [-0.1483, -0.0286],
        [-0.8373,  0.7191],
        [-0.8584,  0.9974],
        [-0.9792,  1.1208],
        [-0.2711, -0.0970],
        [-1.0292,  1.0461],
        [-1.0244,  0.9672],
        [-0.4921,  0.2198],
        [-0.4090, -0.0157],
        [-0.9025,  1.0728],
        [-0.8988,  1.0212],
        [-0.6711,  0.5679],
        [-1.0450,  1.2880],
        [-0.5318,  0.1824],
        [-0.8975,  1.0605],
        [-0.9369,  0.9721],
        [-1.0233,  1.1126],
        [-0.7729,  0.8245],
        [-1.0247,  1.1950],
        [-0.7897,  0.8876],
        [-1.0191,  1.0285],
        [-0.5525,  0.3465],
        [-0.9377,  1.0897],
        [-0.7915,  0.8292],
        [-0.9751,  0.9985],
        [-0.7875,  0.8705],
        [-0.2532, -0.0899],
        [-0.5944,  0.2649],
        [-0.5111,  0.3532],
        [-0.6422,  0.2132],
        [-0.8966,  0.9420],
        [-0.9749,  1.1193],
        [-1.0327,  1.2407],
        [-0.9709,  1.1522],
        [-0.5856,  0.2855],
        [-0.7732,  0.7692],
        [-0.5456,  0.3134],
        [-0.0779, -0.2068],
        [-0.9289,  1.0483],
        [-0.4246,  0.1133],
        [-0.8725,  0.9977],
        [-0.4136,  0.0773],
        [-0.9560,  0.9994],
        [-0.0369, -0.3442],
        [-0.9435,  1.0038],
        [-0.8673,  0.8898],
        [-1.1547,  1.2613],
        [-0.9628,  0.9947],
        [-0.9801,  1.1720],
        [-0.9878,  0.9856],
        [-0.5124,  0.5447],
        [-0.0313, -0.1602],
        [-1.0235,  0.9837],
        [-0.5296,  0.2089],
        [-0.7555,  0.8144],
        [-0.8703,  0.7801],
        [-0.9982,  1.1567],
        [-0.8821,  1.0987],
        [-0.5362,  0.5587],
        [-0.5518,  0.3363],
        [-0.9973,  1.0089],
        [-0.4026,  0.1266],
        [-0.4421,  0.1005],
        [-0.6889,  0.5360],
        [-0.9157,  1.0628],
        [-0.8464,  0.8403],
        [-0.8305,  0.7776],
        [-0.9483,  1.0003],
        [-0.6735,  0.3228],
        [-1.0740,  1.2422],
        [-0.4653,  0.2215],
        [-1.0716,  1.1800],
        [-0.6308,  0.3848],
        [-1.0487,  1.0074],
        [-0.2260,  0.0364],
        [-0.1769, -0.2790],
        [-0.3748,  0.0247],
        [-0.8759,  0.9171],
        [-0.8407,  0.8043],
        [-0.8901,  0.9374],
        [-0.8932,  1.0955],
        [-1.0709,  1.1878],
        [-0.9414,  0.9338],
        [-0.4210,  0.2882],
        [-0.7500,  0.9018],
        [-0.9947,  1.1539],
        [-0.6978,  0.6465],
        [-0.9052,  1.0774],
        [-1.0344,  1.2470],
        [-0.8384,  0.7179],
        [-0.3092, -0.0322],
        [-0.6302,  0.6137],
        [-0.8809,  1.0088],
        [-0.8312,  0.8289],
        [-0.8252,  0.8491],
        [-0.4835,  0.3065],
        [-0.9551,  1.0124],
        [-0.9465,  1.0015],
        [-0.7735,  0.8865],
        [-0.9951,  1.0751],
        [-0.4962,  0.1561],
        [-0.8561,  0.9329],
        [-0.5076,  0.3245],
        [-0.6591,  0.4749],
        [-0.5822,  0.4059],
        [-0.7994,  0.5871],
        [-0.8794,  1.1770],
        [-1.0072,  1.2190],
        [-1.0854,  1.1511],
        [-1.0866,  1.1836],
        [-1.0124,  1.2512],
        [-0.4550,  0.3209],
        [-0.0301, -0.2994],
        [-0.8438,  0.6593],
        [-0.8012,  0.8288],
        [-0.9099,  1.1077],
        [-0.8198,  0.6836],
        [-0.5748,  0.4705],
        [-0.6571,  0.4239],
        [-0.8153,  0.8552],
        [-0.5593,  0.2608],
        [-0.6098,  0.5288],
        [-1.0211,  1.1074],
        [-1.0529,  1.0111],
        [-0.6023,  0.4362],
        [-0.9013,  0.9893],
        [-0.8354,  0.9077],
        [-0.6308,  0.6378],
        [-0.5415,  0.2981],
        [-1.0741,  1.0118],
        [-0.8931,  0.9367],
        [-0.7521,  0.8666],
        [-0.8274,  0.9707],
        [-0.8938,  0.9618],
        [-0.8455,  0.9473],
        [-0.8489,  0.9516],
        [-1.0834,  1.0369],
        [-1.0186,  1.3023],
        [-0.8351,  0.9705],
        [-0.5354,  0.4094],
        [-0.9318,  0.9832],
        [-0.8792,  0.8784],
        [-0.6511,  0.4718],
        [-0.8998,  0.9574],
        [-0.4794,  0.1687],
        [-0.9020,  1.0023],
        [-0.8433,  0.9090],
        [-0.8229,  0.7191],
        [-0.5474,  0.3081],
        [-0.6663,  0.5252],
        [-0.4463,  0.5745],
        [-0.9864,  1.1021],
        [-0.7449,  1.0271],
        [-0.2955, -0.0660],
        [-0.8987,  0.8803],
        [ 0.0114, -0.3830],
        [-0.4612,  0.1993],
        [-0.8983,  0.9338],
        [-0.4763,  0.2478],
        [-0.9833,  1.1246],
        [-0.9744,  1.0157],
        [-0.4451,  0.3405],
        [-0.2575, -0.1126],
        [-0.8331,  0.8246],
        [-0.3432,  0.0996],
        [-0.3868,  0.0835],
        [-0.4727,  0.1944],
        [-0.1675, -0.2098],
        [-0.3722,  0.1655],
        [-0.3971,  0.1145],
        [-1.0408,  1.1486],
        [-0.8629,  0.7499],
        [-0.9502,  0.9271],
        [-0.5895,  0.3481],
        [-0.5490,  0.2865],
        [-0.6740,  0.3897],
        [-0.6360,  0.5265],
        [-0.9129,  0.9956],
        [-0.9855,  0.8902],
        [-0.9046,  1.1291],
        [-0.9622,  1.0447],
        [-0.9278,  0.8858],
        [-0.8643,  0.8372],
        [-0.8110,  0.9993],
        [-0.9885,  0.7963],
        [-0.8387,  0.8551],
        [ 0.0825, -0.5776],
        [-0.3023, -0.0451],
        [-0.3934,  0.0751],
        [-0.6471,  0.4321],
        [-0.8901,  0.9923],
        [-0.8942,  0.9375],
        [-0.9214,  0.8299],
        [-0.4168,  0.1439],
        [-0.8921,  1.0226],
        [-0.6174,  0.3371],
        [-1.0650,  1.1225],
        [-0.6923,  0.7535],
        [-0.8944,  0.9027],
        [-0.6315,  0.7261],
        [-0.9760,  1.0954],
        [-0.7354,  0.7747],
        [-0.7434,  0.7969],
        [-0.1829, -0.2343],
        [-0.6911,  0.4980],
        [ 0.0474, -0.3416],
        [-0.6541,  0.6315],
        [-0.8704,  1.0181],
        [-0.5477,  0.3883],
        [-1.0201,  1.2865],
        [-0.8976,  1.0450],
        [-0.9668,  0.9828],
        [-1.0357,  0.9651],
        [-0.6942,  0.7369],
        [-0.9412,  0.9703],
        [-1.0135,  1.0291],
        [-0.3638, -0.0326],
        [-0.8275,  0.7764],
        [-0.8662,  1.1372],
        [-0.7643,  0.6467],
        [-0.9349,  1.1058],
        [-0.4948,  0.4538]], device='mps:0', grad_fn=<LinearBackward0>), hidden_states=None, attentions=None)

In [25]:
torch.argmax(outputs.logits, axis=1), outputs.loss, eval_dataloader.dataset['label'][-batch_size:]
# torch.argmax(outputs.logits, -1).detach().cpu().numpy()
# torch.argmax(outputs.logits, -1).detach().cpu().numpy()

(tensor([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0], device='mps:0'),
 tensor(0.0269, device='mps:0'),
 [1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2])

### RETRY

In [148]:
from transformers import AutoModelForSequenceClassification
from peft import PeftModel
from transformers import (AutoTokenizer
                          , AutoModelForSequenceClassification
                          , BertForSequenceClassification
                          , Trainer
                          , TrainingArguments
)
from transformers import default_data_collator, get_linear_schedule_with_warmup
from transformers import AutoModelForSeq2SeqLM
from peft import get_peft_config, get_peft_model, LoraConfig, TaskType

In [ ]:

def preprocess_function(examples):
    inputs = examples['sentence']
    targets = examples['label']
    model_inputs = tokenizer(
        inputs, 
        padding="max_length", 
        max_length=256, 
        truncation=True,
        return_tensors="pt"
    )
    model_inputs["labels"] = targets
    return model_inputs




model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=3  # specify number of labels
)
peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=32,
    lora_dropout=0.1,
    target_modules=["query", "value"],  # fix the syntax here
)


learning_rate = 2e-5
batch_size = 8
num_epochs = 6

def preprocess_function(examples):
    inputs = examples['sentence']
    targets = examples['label']
    model_inputs = tokenizer(
        inputs, 
        padding="max_length", 
        max_length=256, 
        truncation=True
    )
    model_inputs["labels"] = targets
    return model_inputs

preprocessed_datasets = dataset.map(
    preprocess_function, 
    batched=True,
    remove_columns=dataset["train"].column_names  # Remove original columns
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 1,181,955 || all params: 110,666,502 || trainable%: 1.0680

TrainOutput(global_step=1530, training_loss=0.7880736008189083, metrics={'train_runtime': 576.2436, 'train_samples_per_second': 21.21, 'train_steps_per_second': 2.655, 'total_flos': 1630074927495168.0, 'train_loss': 0.7880736008189083, 'epoch': 6.0})

In [147]:

# Create the base model
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=3
)

# Training arguments
training_args = TrainingArguments(
    output_dir="default_bert_trainer",
    overwrite_output_dir=True,
    do_train=True,
    do_eval=True,
    eval_strategy='epoch',
    logging_strategy='epoch',
    per_device_eval_batch_size=batch_size,
    per_device_train_batch_size=batch_size,
    learning_rate=learning_rate,
    optim='adamw_torch',
    num_train_epochs= num_epochs
)

# Create and start trainer
trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=preprocessed_datasets['train'],
    eval_dataset=preprocessed_datasets['validation'],
    compute_metrics=compute_metrics,
)
trainer.train()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

TrainOutput(global_step=1530, training_loss=0.5919771580914267, metrics={'train_runtime': 353.2897, 'train_samples_per_second': 34.595, 'train_steps_per_second': 4.331, 'total_flos': 1630074927495168.0, 'train_loss': 0.5919771580914267, 'epoch': 6.0})

In [152]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [161]:
trainer.save_model('default_bert_model')
pre_model = AutoModelForSequenceClassification.from_pretrained('default_bert_model', num_labels=3)
pre_model.to(device)

t = tokenizer(dataset['validation']['sentence'], padding=True, truncation=True,return_tensors='pt')
t.to(device)
outputs = pre_model(**t)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [169]:
compute_metrics((outputs.logits.cpu().detach().numpy(),dataset['validation']['label'] ))

{'accuracy': np.float64(0.7929515418502202)}

In [ ]:

# Create LoRA config
peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=32,
    lora_dropout=0.1,
    target_modules=["query", "value"]
)

# Create LoRA model
lora_model = get_peft_model(model, peft_config)
lora_model.print_trainable_parameters()

# Training arguments
training_args = TrainingArguments(
    output_dir="bert_peft_trainer",
    overwrite_output_dir=True,
    do_train=True,
    do_eval=True,
    eval_strategy='epoch',
    logging_strategy='epoch',
    per_device_eval_batch_size=batch_size,
    per_device_train_batch_size=batch_size,
    learning_rate=learning_rate,
    optim='adamw_torch',
    num_train_epochs= num_epochs
)

# Create and start trainer
trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=preprocessed_datasets['train'],
    eval_dataset=preprocessed_datasets['validation'],
    compute_metrics=compute_metrics,
)

trainer.train()

In [145]:
trainer.save_model("bert_classifier_final")
from peft import PeftModelForSequenceClassification
loaded_model = PeftModelForSequenceClassification.from_pretrained(model, "bert_classifier_final")

In [140]:
outputs = model(**validation_tokenized)

In [125]:
from peft import PeftModel
validation_tokenized = tokenizer(dataset['validation']['sentence'], padding=True, truncation=True, return_tensors='pt')
validation_tokenized.to(device)
print(validation_tokenized)
outputs = lora_model(**validation_tokenized)

{'input_ids': tensor([[ 101, 1996, 3643,  ...,    0,    0,    0],
        [ 101, 1996, 2034,  ...,    0,    0,    0],
        [ 101, 1996, 2707,  ...,    0,    0,    0],
        ...,
        [ 101, 6983, 2924,  ...,    0,    0,    0],
        [ 101, 1996, 3155,  ...,    0,    0,    0],
        [ 101, 1996, 3930,  ...,    0,    0,    0]], device='mps:0'), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='mps:0'), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='mps:0')}

In [ ]:
# torch.argmax(outputs.logits, axis=1)
# dataset['validation']['label']

{'accuracy': np.float64(0.7841409691629956)}

array([[-1.084637  ,  1.225609  , -0.23401234],
       [-1.3039601 ,  1.5671574 , -0.33476457],
       [-1.5006039 ,  1.7496247 , -0.34419644],
       [-1.7290581 ,  2.198359  , -0.47018084],
       [-1.3103527 ,  1.5316836 , -0.2397772 ],
       [-1.7601162 ,  2.0357747 , -0.47549322],
       [-1.7846684 ,  2.1045642 , -0.44123933],
       [ 0.13353984, -0.9340858 ,  0.56161475],
       [-1.4412314 ,  1.6570082 , -0.25146088],
       [-1.4308376 ,  1.6029435 , -0.23897733],
       [ 0.3216268 , -0.57214457,  0.45171106],
       [-1.5779785 ,  1.8594652 , -0.43725443],
       [-1.7594473 ,  2.0528474 , -0.43187714],
       [-1.5991194 ,  1.7676309 , -0.4362293 ],
       [-1.3235259 ,  1.7682623 , -0.29320532],
       [-1.4991641 ,  1.7631754 , -0.34189615],
       [-1.2857355 ,  1.5507592 , -0.22653385],
       [-1.4667878 ,  1.749101  , -0.3185767 ],
       [-1.7712188 ,  1.9505816 , -0.45475614],
       [-0.4659963 ,  0.56659603,  0.11594266],
       [-1.0026724 ,  1.2378708 , -0.17654552],
       [-1.8393276 ,  2.0680823 , -0.5019439 ],
       [-1.6667154 ,  1.9220377 , -0.35086435],
       [ 0.34671816, -0.52788574,  0.41876268],
       [-1.0342921 ,  1.2670074 , -0.19383188],
       [-1.0970513 ,  1.4044936 , -0.32326502],
       [-1.2655432 ,  1.4577013 , -0.34851724],
       [-0.16641083,  0.02918034,  0.1325634 ],
       [ 0.29199204, -1.1877455 ,  0.7053795 ],
       [-1.570957  ,  1.7256048 , -0.3927174 ],
       [-1.4612908 ,  1.9012392 , -0.31939316],
       [-1.7764436 ,  2.18875   , -0.5155093 ],
       [-1.3379307 ,  1.4938012 , -0.24167062],
       [ 0.27951002, -0.33708206,  0.34602243],
       [-0.6670786 ,  0.771604  , -0.12553538],
       [ 0.11825596, -1.4948685 ,  0.8592289 ],
       [-1.6868474 ,  1.8859524 , -0.48656487],
       [-1.690424  ,  1.898836  , -0.44124046],
       [-0.36198753,  0.5002089 ,  0.01769054],
       [-1.3129071 ,  1.6430367 , -0.23008329],
       [ 0.53769886, -1.9525238 ,  0.97463274],
       [-1.7446864 ,  2.0417407 , -0.43963677],
       [-0.5075114 ,  0.72236305,  0.04452461],
       [ 0.41792122, -1.7030334 ,  0.90139604],
       [-0.5765506 ,  0.9595061 , -0.10481814],
       [-1.8462498 ,  2.0879812 , -0.4949501 ],
       [-1.5840755 ,  1.7990807 , -0.41661608],
       [-1.7095149 ,  1.9017433 , -0.39598417],
       [-1.3677306 ,  1.6820556 , -0.3162294 ],
       [-1.6838815 ,  1.9715706 , -0.40183386],
       [-0.04262548, -0.01950723,  0.18664809],
       [-0.32246405,  0.22804117,  0.0406292 ],
       [ 0.36882195, -1.6069938 ,  0.913482  ],
       [-0.6418917 ,  0.8603036 ,  0.02431976],
       [ 0.22676031, -1.6528963 ,  0.93820673],
       [ 0.30509   , -1.5378696 ,  0.8571931 ],
       [-0.55176425,  0.85827076, -0.09553982],
       [ 0.2573364 , -0.4524673 ,  0.3849067 ],
       [-1.6608918 ,  1.8470646 , -0.3812061 ],
       [-1.6157627 ,  1.8638693 , -0.36767733],
       [-1.210413  ,  1.3975687 , -0.15880746],
       [-1.7243794 ,  1.9285212 , -0.42117417],
       [-0.8289946 ,  1.1174946 , -0.16735616],
       [-0.8765239 ,  1.1134211 , -0.16978268],
       [-0.43851605,  0.35373554,  0.05587709],
       [ 0.10729061, -0.50075036,  0.3693867 ],
       [ 0.42649353, -1.812389  ,  0.9312587 ],
       [ 0.41356513, -1.8638328 ,  0.92794156],
       [-0.7392935 ,  0.90400654, -0.03821001],
       [ 0.24389686, -0.87002033,  0.5606709 ],
       [-1.5726314 ,  1.8624781 , -0.35596496],
       [-1.4870558 ,  1.7786187 , -0.35275802],
       [-1.2785218 ,  1.3011692 , -0.32674572],
       [ 0.11172515, -0.20777929,  0.289691  ],
       [-1.8189057 ,  2.038148  , -0.45893553],
       [-1.8027142 ,  2.00367   , -0.48305047],
       [-1.7705483 ,  1.9493631 , -0.45362273],
       [ 0.2072161 , -1.4383101 ,  0.8145386 ],
       [ 0.3453168 , -1.7294124 ,  0.90879864],
       [-0.6896544 ,  0.78690267, -0.03168387],
       [-1.7599385 ,  2.1081812 , -0.46227723],
       [-0.9892983 ,  1.4276499 , -0.26343113],
       [-0.97592354,  1.1007792 , -0.12503166],
       [-1.8662046 ,  2.148216  , -0.49060744],
       [-0.9673067 ,  1.3505573 , -0.19942944],
       [-1.5612874 ,  1.9869181 , -0.49229866],
       [-1.5608761 ,  1.8245199 , -0.40746248],
       [-1.5835993 ,  1.9549648 , -0.40491593],
       [-1.0677097 ,  1.5585486 , -0.20870082],
       [-1.2801883 ,  1.5179774 , -0.2827785 ],
       [ 0.23251428, -1.3129385 ,  0.7716413 ],
       [-1.7923509 ,  2.0221007 , -0.43283755],
       [-0.55363625,  0.47995657,  0.08367891],
       [-1.7624264 ,  1.9837111 , -0.48778898],
       [-1.513556  ,  1.8031806 , -0.3642053 ],
       [ 0.30491868, -0.4464859 ,  0.40188676],
       [-1.7354848 ,  1.982514  , -0.46914253],
       [-0.8574123 ,  0.9014271 , -0.07062364],
       [-1.6154149 ,  1.9393703 , -0.37506214],
       [-1.1301048 ,  1.4889454 , -0.3218596 ],
       [ 0.13561505, -1.0930485 ,  0.6546153 ],
       [ 0.53975886, -1.9549093 ,  0.9214431 ],
       [-1.582118  ,  1.8440386 , -0.37613836],
       [-1.7385494 ,  2.0089517 , -0.4394173 ],
       [-0.69904184,  0.83471894, -0.02417002],
       [-1.5399983 ,  1.7686859 , -0.41576624],
       [-1.6736537 ,  1.970516  , -0.49840856],
       [-1.8381271 ,  2.1493964 , -0.48059538],
       [-1.488909  ,  1.7407799 , -0.44092816],
       [-1.3459644 ,  1.5571866 , -0.27363664],
       [-1.8977273 ,  2.2555494 , -0.5080901 ],
       [ 0.3474618 , -1.7211007 ,  0.9312598 ],
       [ 0.2989086 , -0.39015958,  0.36676812],
       [ 0.35008612, -1.6470431 ,  0.9131659 ],
       [-1.6657667 ,  1.9732655 , -0.47232127],
       [-0.61024266,  0.7443429 , -0.0525419 ],
       [-1.2732542 ,  1.6752635 , -0.30112883],
       [-1.8026855 ,  2.0192    , -0.4673819 ],
       [-1.3217728 ,  1.5646197 , -0.36955056],
       [-1.3381822 ,  1.641758  , -0.39833826],
       [-1.8100917 ,  2.1549928 , -0.48635307],
       [-1.299593  ,  1.5207192 , -0.27385384],
       [-1.6586304 ,  1.8198122 , -0.462606  ],
       [-1.370389  ,  1.651976  , -0.28140843],
       [-1.7521977 ,  2.2652678 , -0.50482804],
       [-1.7770073 ,  2.226079  , -0.5311054 ],
       [-0.4675569 ,  0.6957818 , -0.03780466],
       [ 0.13380459, -0.4552043 ,  0.38969618],
       [-1.873802  ,  2.1053152 , -0.49314964],
       [-1.4334501 ,  1.6335324 , -0.30186653],
       [-1.575688  ,  1.8219105 , -0.39956647],
       [ 0.06264413, -0.03097288,  0.27319944],
       [-1.3567712 ,  2.0082479 , -0.34273732],
       [-1.8722147 ,  2.2857533 , -0.554399  ],
       [-1.7744248 ,  1.9913412 , -0.44985783],
       [-1.4633206 ,  1.6148307 , -0.30517906],
       [-0.3081003 ,  0.4573999 ,  0.10085088],
       [ 0.32975212, -1.5675777 ,  0.81033134],
       [ 0.34702453, -1.848812  ,  0.93934166],
       [-1.353757  ,  1.6949637 , -0.34491473],
       [ 0.27946523, -1.4060875 ,  0.82847416],
       [ 0.30261365, -0.93633574,  0.59899974],
       [-0.35485226,  0.4468267 ,  0.10837259],
       [-0.5220702 ,  0.372612  ,  0.13109306],
       [ 0.38460347, -1.6986712 ,  0.88439256],
       [-1.7243183 ,  2.0263135 , -0.39601836],
       [ 0.2940439 , -0.42729506,  0.34719187],
       [-1.6099343 ,  1.9182951 , -0.3872326 ],
       [-0.17845744, -0.00978418,  0.23291521],
       [-0.29272804,  0.5095474 , -0.00584955],
       [ 0.19702683, -0.2821428 ,  0.30738297],
       [-1.870863  ,  2.1823628 , -0.5746772 ],
       [-0.46756905,  0.40502536,  0.144437  ],
       [-1.6407056 ,  1.9355947 , -0.4486094 ],
       [ 0.39885363, -1.7321991 ,  0.90662014],
       [-1.5619835 ,  1.8631734 , -0.34198648],
       [ 0.12547235, -1.2749234 ,  0.67275167],
       [-1.7329385 ,  1.8709785 , -0.41070867],
       [-1.3498312 ,  1.6284028 , -0.27344236],
       [-1.5672028 ,  1.7997348 , -0.35148743],
       [ 0.25802362, -0.38206404,  0.36833775],
       [ 0.21197224, -0.46670306,  0.384082  ],
       [-0.21910493,  0.2518453 ,  0.13257354],
       [-1.4081862 ,  1.8767631 , -0.40657   ],
       [-0.37018895,  0.25837916,  0.13518615],
       [ 0.39901215, -1.7741308 ,  0.92949736],
       [-1.6930149 ,  2.0127873 , -0.502149  ],
       [-0.6531691 ,  0.9462392 , -0.09919757],
       [-1.3646154 ,  1.6051491 , -0.30481234],
       [ 0.08664149, -0.15875615,  0.31401503],
       [-1.7681404 ,  2.0726523 , -0.470644  ],
       [ 0.14453423, -0.8797415 ,  0.55837893],
       [-1.6963481 ,  2.2407005 , -0.44784957],
       [-1.6558616 ,  1.9350523 , -0.46791527],
       [-1.4511757 ,  1.6273385 , -0.335917  ],
       [-1.6747484 ,  1.8953723 , -0.40744695],
       [ 0.15005764, -0.2642779 ,  0.25924736],
       [-1.7750717 ,  1.9586703 , -0.44189706],
       [-1.0765406 ,  1.0021832 , -0.13768825],
       [-0.84991   ,  1.2088828 , -0.19864939],
       [-1.545772  ,  1.765036  , -0.3531436 ],
       [-1.0359817 ,  1.3172736 , -0.27238032],
       [-1.554579  ,  1.8541416 , -0.3237514 ],
       [-1.6789165 ,  1.8823587 , -0.3614785 ],
       [-0.4935627 ,  0.45238948,  0.05040209],
       [-1.6629254 ,  1.8835137 , -0.38114765],
       [-1.3395168 ,  1.575732  , -0.29882756],
       [-1.5605662 ,  1.8283688 , -0.41329682],
       [-1.330102  ,  1.4926351 , -0.27092516],
       [-1.8451304 ,  2.1023817 , -0.48421562],
       [-1.1282502 ,  1.3307387 , -0.25059754],
       [-0.2892029 ,  0.29891187,  0.13147053],
       [-1.7294533 ,  1.9912937 , -0.4476147 ],
       [-1.4585721 ,  1.7431633 , -0.3093219 ],
       [-1.7651695 ,  2.196981  , -0.44546187],
       [-1.662089  ,  2.0657845 , -0.46050388],
       [-1.7519639 ,  1.9610679 , -0.41451675],
       [-1.8161767 ,  2.1404462 , -0.48616946],
       [-1.849764  ,  2.1697307 , -0.49073115],
       [-1.052835  ,  1.5129013 , -0.15007444],
       [-1.099706  ,  1.250028  , -0.1344109 ],
       [-1.5661478 ,  1.8956524 , -0.4196805 ],
       [-1.1403925 ,  1.1576202 , -0.16597396],
       [-1.779499  ,  2.1659553 , -0.4373471 ],
       [-1.4444793 ,  1.8886055 , -0.36524773],
       [ 0.27730876, -1.3152882 ,  0.7556318 ],
       [-1.9209726 ,  2.134165  , -0.5101852 ],
       [-1.6291901 ,  2.010373  , -0.48224702],
       [-1.7597307 ,  2.0853844 , -0.45634115],
       [-0.910919  ,  0.9726493 , -0.09767628],
       [-1.6576272 ,  1.9972023 , -0.35710517],
       [-1.7545943 ,  2.1578915 , -0.49439973],
       [ 0.13997316, -0.12922439,  0.32136708],
       [-0.12628344,  0.0727019 ,  0.18485719],
       [-1.8157301 ,  2.0474489 , -0.46379536],
       [-1.9801123 ,  2.2466793 , -0.53671944],
       [-1.9022864 ,  2.2778664 , -0.5068456 ],
       [-1.7421746 ,  2.0237377 , -0.48427683],
       [-1.4078057 ,  1.5005864 , -0.2868997 ],
       [-1.4760807 ,  1.7142004 , -0.37764424],
       [-1.5292192 ,  2.0811403 , -0.34794104],
       [ 0.5391513 , -1.9682621 ,  1.0075271 ],
       [-0.793838  ,  1.0511154 ,  0.00462612],
       [-1.1502641 ,  1.3475496 , -0.2571328 ],
       [-1.4698261 ,  1.7622114 , -0.33198184],
       [-1.7393501 ,  1.9300858 , -0.39662763],
       [-1.0424969 ,  1.2895224 , -0.16058119]], dtype=float32)

In [117]:
lora_model

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): BertForSequenceClassification(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30522, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=32, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=32, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=32, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=32, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (activation): Tanh()
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=3, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=3, bias=True)
        )
      )
    )
  )
)

In [58]:
# print accuracy
correct = 0
total = 0
for pred, true in zip(eval_preds, dataset["validation"]['label']):
    if pred == true:
        correct += 1
    total += 1
accuracy = correct / total * 100
print(f"{accuracy=} % on the evaluation dataset")

accuracy=45.81497797356828 % on the evaluation dataset

In [60]:

reloaded_lora = original_with_adapter = PeftModel.from_pretrained(
  original_model, "bert-peft" # bert-peft; the folder of the saved adapter
)

reloaded_lora = reloaded_lora.to(device)

In [ ]:
with torch.no_grad():
    reloaded_lora(**)

In [ ]:
from peft import AutoPeftModelForSequenceClassification, AutoPeftModelForSeq2SeqLM
device='mps'

reloaded_lora = AutoPeftModelForSequenceClassification.from_pretrained('./lora_pretrained'
                                                                       , is_trainable=False
                                                                       ,num_labels=len(dataset["train"].features["label"].names)
                                                                       )
reloaded_lora = reloaded_lora.to(device)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

RuntimeError: Error(s) in loading state_dict for PeftModelForSequenceClassification:
	size mismatch for base_model.model.classifier.modules_to_save.default.weight: copying a param with shape torch.Size([2, 768]) from checkpoint, the shape in current model is torch.Size([3, 768]).
	size mismatch for base_model.model.classifier.modules_to_save.default.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).

In [ ]:
lora_model.config.num_lae

In [63]:
from datasets import Dataset
few_shot_examples = {"sentence" : ['the bull market is starting to look like a bear',
                        'Stocks went in the direction of -100bps',
                        'we can see nvidia is gaining steam event with the government cracking down',
                        'wow, buy this stock now - its gone up 500% and continuing to grow',

                        ],
         "label" : [0,0,2,2]
        }

fse = Dataset.from_dict(few_shot_examples)
new_examples= fse.map(preprocess_function, batched=True, remove_columns=['sentence','label'], keep_in_memory=False)
new_examples = new_examples.with_format("torch", device=device)
# new_examples.to(device)

new_examples

Map: 100%|██████████| 4/4 [00:00<00:00, 1489.19 examples/s]

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 4
})

In [64]:
fse['sentence']

['the bull market is starting to look like a bear',
 'Stocks went in the direction of -100bps',
 'we can see nvidia is gaining steam event with the government cracking down',
 'wow, buy this stock now - its gone up 500% and continuing to grow']

In [65]:
fse = fse.with_format("torch", device=device)
ds = tokenizer(fse['sentence'], max_length=512, padding=True , truncation=True, return_tensors='pt')
ds = ds.to(device)
# ds = Dataset.from_dict(tokenizer(fse['sentence'])).with_format("torch", device=device)

AttributeError: 'BertForSequenceClassification' object has no attribute 'batch'

In [115]:
# tokenizer(dataset['validation']
tokenized_val = tokenizer(dataset['validation']['sentence'], return_tensors='pt', padding=True, truncation=True)        
tokenized_val.to(device)  
new_outputs = reloaded_lora(**tokenized_val)

new_outputs.logits.argmax(axis=1)

tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0], device='mps:0')

In [104]:
reloaded_lora.eval()

# tokenizer(fse)
with torch.no_grad():
        new_outputs = reloaded_lora(**preprocessed_datasets['validation'])

with torch.no_grad():
        old_model_outputs = model(**preprocessed_datasets['validation'])

new_outputs, old_model_outputs

TypeError: PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): BertForSequenceClassification(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30522, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (activation): Tanh()
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
    )
  )
) argument after ** must be a mapping, not Dataset

In [ ]:
a = preprocessed_datasets['validation']

{'sentence': ['The first stage of the contract covers 133 stores and 600 cash registers .',
  'Unbelievably , the company that makes them - Fiskars Corporation - was formed in 1649 when a Dutch merchant named Peter Thorwoste was given a charter to establish a blast furnace and forging operation in the small Finnish village of Fiskars .',
  "One price category is for calls on the preferred operator 's network , and another for calls on other operators ' networks .",
  "`` This is a significant milestone for Benefon , helping us to secure critical USP 's for our personal navigation product roadmap for 2007 and beyond , '' commented Simon Button , Chief Technology Officer at Benefon .",
  "Maggie Ramsey 's wait - and those of thousands of Oregon and Washington guides , anglers and others who flock to his frequent seminars - is nearly over .",
  "In the second quarter of 2010 , Raute 's net loss narrowed to EUR 123,000 from EUR 1.5 million in the same period of 2009 .",
  'As an alternative to the share exchange , Panostaja offers a full cash consideration at the value of 1.27 euro $ 1.7 per share .',
  "At the request of Finnish media company Alma Media 's newspapers , research manager Jari Kaivo-oja at the Finland Futures Research Centre at the Turku School of Economics has drawn up a future scenario for Finland 's national economy by using a model developed by the University of Denver .",
  'Arena Partners Oy is a development company for electronic business .',
  'Both operating profit and net sales for the three-month period increased , respectively from EUR15 .1 m and EUR131 .5 m , as compared to the corresponding period in 2005 .',
  'Additionally , the company will use the solutions to automate the preparation of financial statements according to IFRS standard .',
  'About Dopplr Dopplr is a service for smart travellers .',
  'In the third quarter , net sales increased by 12 % year-on-year to EUR 159.5 million , or by 6 % at comparable currency rates growth .',
  'Finnish consumer packaging manufacturer Huhtamaki Oyj said it swung to a net profit of 84.1 mln euro $ 105.6 mln in the first nine months of 2006 from a net loss of 2.6 mln euro $ 3.3 mln in the same period of 2005 .',
  'The restructuring creates a more efficient organization with increased operational focus and stable profitability , and leads to more efficient production , said Bo Annvik , head of Specialty Stainless .',
  'Officials did not disclose the contract value .',
  'Nordstjernan will make the offer in approximately one month , in September 2007 .',
  'Exel is headquartered in Mantyharju in Finland .',
  "EQ Bank forecasts Olvi 's net sales at EUR 67mn in the second quarter of 2009 , and operating profit at EUR 6.4 mn .",
  'The bank VTB24 provides mortgage loans to buy apartments in the complex at 11-13 % per annum in rubles .',
  'The Tecnomen Convergent Charging solution includes functionality for prepaid and post-paid billing , charging and rating of voice calls , video calls , raw data traffic and any type of content services in both mobile and fixed networks .',
  'The gross area of eight houses will be 12,167 m2 .',
  'He confirmed his view on July 6 .',
  'Componenta is a metal sector company with international operations and production plants located in Finland , the Netherlands , Sweden and Turkey .',
  'The increase range will vary up to 10 % .',
  "The business section also includes Ahlstrom 's sustainability report .",
  'Nordea sees a return to positive growth for the Baltic countries in 2011 .',
  'The solution will be installed in the USA to support the North American operations of the customer .',
  'The commission said the hydrogen peroxide and PBS market was worth about 470 million euros in 2000 .',
  'Technopolis has approximately 130 customer companies in Jyvaskyla .',
  'The share capital of Alma Media Corporation (business ID 1944757-4)is EUR 45,031,513.80 and it is divided into 75,052,523 shares .',
  'Operating profit totaled EUR 37,7 mn , up slightly from EUR 37.2 mn in the corresponding period in 2006 .',
  "The fair value of the company 's investment properties went down to EUR2 .769 bn at the end of September 2009 from EUR2 .878 bn a year earlier .",
  'Finnish financial software solutions developer BasWare Oyj said its net profit fell to 884,000 euro ( $ 1.2 mln ) for the first quarter of 2007 from 2.0 mln euro ( $ 2.7 mln ) a year earlier .',
  'Combined net sales in 2006 were $ 27 million and EBITDA was $ 13.7 million .',
  'The business transfer will take effect from 1 January 2007 , and in connection with this 47 employees will transfer from Elisa to Daxtum as continuing employees .',
  'Alpina Sports is a Lebanon , New Hampshire USA based distributor of e.g. Alpina ski shoes and skis , Exel ski poles , Start ski waxes and now also Peltonen cross-country skis .',
  'The company was supposed to deliver machinery to a veneer mill in the Tomsk region , in Russia .',
  'According to the Finnish-Russian Chamber of Commerce , all the major construction companies of Finland are operating in Russia .',
  'Operating profit totaled EUR 825mn , up from EUR 763mn in 2004 .',
  "Swedbank 's shares have been hardest hit of the Swedish banks by the ongoing international financial crisis .",
  'Boomerang Boats had net sales of EUR 4.1 mn and it made an operating profit of EUR 0.4 mn in 2006 .',
  'Profit for the period was EUR 9.8 mn , up from EUR 6.0 mn in 2004 .',
  'The Financial Statements and Interim Reports will be released around at 9.00 a.m. ( Finnish time ) on the given dates .',
  'Finnish pulp and paper machinery maker Vaahto Group Oyj swung to a 1.1 mln euro $ 1.4 mln net profit in the fiscal 2005-06 , ended August 31 , 2006 , from a 249,000 euro $ 319,000 net loss in the fiscal 2004-05 .',
  'No financial details were revealed .',
  '1 February 2011 - Finnish textile and clothing company Marimekko Oyj HEL : MMO1V said today its preliminary operating profit grew to EUR8 .2 m in 2010 from EUR6 .3 m in 2009 .',
  'Sanoma Magazines International will invite other shareholders holding approximately 15 % of the shares to sell their shares .',
  "Finnish plumbing and heating systems supplier Uponor 's net sales from continuing operations decreased by 9.4 % in 2008 to EUR 949.2 mn from EUR 1,047.4 mn in 2007 .",
  "HELSINKI AFX - Outokumpu said its technology unit has won a 28 mln eur contract from Bosnia-Herzegovina 's Aluminij dd Mostar to upgrade an anode plant .",
  'The objective is that trading in the shares will commence on May 2 , 2007 .',
  'The company specialises in temporary electrification and heating at construction sites .',
  'NWC ANALYSIS :',
  'Viking Line manages well with its current ferries .',
  "The bond , with a maturity of five years , is part of the bank 's domestic bond program .",
  'International sales rose by 59.8 % to EUR 1,244.4 mn .',
  "Exel 's board of directors will propose a dividend of 0.2 euro $ 0.3 per share for 2006 at the annual general meeting on April 19 , 2007 .",
  'This wood lacquered clock comes with a stripy hand-crocheted cover .',
  'In the first quarter of 2010 , the mark-to-market result was a pretax profit of EUR 133 million versus a loss of EUR 32 million in the same period last year .',
  'Mika Stahlberg , VP F-Secure Labs , said , `` We are excited and proud that F-Secure has been recognized by AV-Comparatives as the Product of the Year .',
  "The subscription period of Amer Sports ' 2002 warrant scheme will end on 31 December 2007 .",
  'Teleste was set up in 1954 and is divided into Broadband Cable Networks and Video Networks business areas .',
  "The new majority owners of Aspocomp Thailand Co. , Ltd are certain private persons belonging to immediate circle of Aspocomp 's present Joint Venture partner , Saha Pathana Inter-Holding Plc. .",
  'H+Ñkan Dahlstr+Âm , head of mobility services at TeliaSonera , has forecast that mobile data volume on the TeliaSonera network in Sweden will rise eight-fold to 200,000 TB by 2014 .',
  'It generated an operating loss of EUR 96.3 mn , down from a profit of EUR 43.9 mn .',
  'Castecka said the town hall would hold talks with other investors interested in the zone .',
  '( ADPnews ) - May 4 , 2010 - Finnish cutlery and hand tools maker Fiskars Oyj Abp ( HEL : FISAS ) said today its net profit declined to EUR 12.9 million ( USD 17m ) in the first quarter of 2010 from EUR 17 million in the correspond',
  'Operating result including non-recurring items rose to EUR 146mn from a loss of EUR 267mn in 2009 .',
  'Excluding non-recurring items , pre-tax profit surged 45 % to EUR80m .',
  'Erkki Jarvinen , President of Rautakirja and the head of the Sanoma Trade division , will leave his current tasks in spring 2009 for a similar position outside the Sanoma Group .',
  'The interim report for the first quarter is published on May 8 , 2009 .',
  'The company will publish its financial statement for 2008 on February 25 , 2009 .',
  "The port facilities ' throughput is 250,000 TEUs and 7.5 mln tons of general cargo .",
  'The last quarter was the best quarter of 2009 in net sales , and the operating margin rose to 12.2 % .',
  'The 19,200-square metre technology center is located near University of Tampere in central Tampere .',
  'Net interest income totaled EUR 15.9 mn , compared to EUR 15.6 mn a year earlier .',
  'The decision reflects the underutilisation of the line , which produces nonwovens used in medical and wipes applications as well as for the automotive industry .',
  'Net sales will , however , increase from 2005 .',
  'The sellers include 40 shareholders , including Intellibis management , employees and other investors .',
  'Finnish business software group AffectoGenimap Oyj said its net profit halved to 1.2 mln euro ( $ 1.5 mln ) in the first nine months of 2006 from 2.2 mln euro ( $ 2.8 mln ) in the same period of 2005 .',
  "Finnish Aktia Group 's operating profit rose to EUR 17.5 mn in the first quarter of 2010 from EUR 8.2 mn in the first quarter of 2009 .",
  'Operating profit totalled EUR 9.0 mn , down from EUR 9.7 mn in the first half of 2008 .',
  'The continued operations mean the structure after the restructuring of the Aspocomp group including Aspocomp Oulu and the headquarter operations .',
  'The Web-Marela application handles invitations to quote , quote comparisons , agreements , purchases , invoice inspections , inventory management , and deliveries .',
  'Latin America currently accounts for approximately 40 % of sales at Tecnotree , company president and CEO Eero Mertano recently told BNamericas .',
  'treatment products in Usa , Canada , Mexico , Australia and Brazil Today , Global Research & Data Services is going to publish several market analyses about the markets for water treatment products in some selected countries .',
  'The mall will be financed on a parity basis by Pearl Plaza LLC , the joint venture company established by the Chinese investor Shanghai Industrial Investment Holdings Co Ltd , and SRV Group .',
  'These financing arrangements will enable the company to ensure , in line with its treasury policy , that it has sufficient financial instruments at its disposal for its potential capital requirements .',
  "Clothing chain Sepp+ñl+ñ 's net sales increased by 7.0 % to EUR 30.8 mn .",
  "Halonen 's office acknowledged receiving the letter but declined comment .",
  'Its product portfolio comprises harvesters , forwarders , harvester heads , as well as cranes and loaders .',
  'Elisa said mobile subscriptions grew 7 percent during 2007 , mainly because of customers adopting so-called third generation mobile technology .',
  'After the transaction , Tikkurila has no powder coatings related operations .',
  'Tekla provides 3D software for building and infrastructure engineering , with a focus on building information modelling of steel and concrete structures from design to construction .',
  'Revenue from July to September grew 21 percent to EURO 2.3 billion , the Finnish company said Thursday .',
  "Quarterly diluted EPS on continuing operations came in at 0.21 eur , compared with last year 's 0.12 eur .",
  'Honkarakenne also decided yesterday to sell 88,500 of its B series shares to key staff members for EUR2 .9 per share .',
  'The transaction is expected to be finalized by Dec 2009 .',
  "The company 's board of directors will propose a dividend of EUR 0.14 for 2008 at the annual general meeting .",
  'The volume of investments in the two phases of the project is estimated at USD 300mn ( EUR 215.03 mn ) .',
  'In the third quarter of 2007 , net sales totaled EUR 25.95 mn , and operating profit EUR 3.88 mn .',
  'Janis Arbidans , CEO of YIT Celtnieciba , said the company was focusing on housing and real estate development market .',
  'The negotiations concern personnel of Cencorp Corporation and Singulase Oy as whole in Finland and in Sweden , the company said .',
  'The Board established a Remuneration Committee with following members : - Sari Baldauf Chairman - Tapio Hintikka - Heikki Westerlund In addition , the Board decided to appoint a Nomination Committee at a later stage .',
  'The agreement strengthens our long-term partnership with Nokia Siemens Networks .',
  'Finnish silicon wafers manufacturer Okmetic Oyj said it swung to a net profit of 4.9 mln euro $ 6.3 mln in the first nine months of 2006 from a net loss of 1.8 mln euro $ 2.3 mln a year earlier .',
  'The executive said that countries such as Brazil , Chile , Argentina and Mexico will lead the adoption in the business Ethernet services segment , while Brazil and Mexico will be the early adopters of carrier Ethernet for mobile backhaul .',
  "`` The enterprise value of the Fray Bentos pulp mill and Forestal Oriental totals approximately euro1 .6 billion , '' UPM said .",
  'The company anticipates its turnover for the whole 2010 to surpass that of the previous year when it was EUR 67.1 million .',
  'Finnish communication electronics components supplier Scanfil Oyj Tuesday said sales in the first half of 2006 will be 15 % lower than during the same period a year ago .',
  'Talentum expects that the net sales of its core business will increase in 2008 , compared to 2007 .',
  "Den Bosch-based TomTom is Europe 's largest maker of automotive navigation devices , while Cayman Islands-based Garmin is larger in the U.S. and overall .",
  'Its customers include local companies Slo Oy , Kiilto Oy , Toptronics Oy , Normark Suomi Oy , Pellonpaja Oy and Mansner Oy .',
  'The phones are targeted at first time users in growth markets .',
  '8,600 m , and at the time of investment it is fully leased to several tenants .',
  'Currently it operates a fleet of eight carriers , as well as nine pushers and barges .',
  'The net sales of Healthcare Trade business in 2009 were EUR 145.1 million EUR 155.2 million and operating profit EUR 8.9 million EUR 7.9 million .',
  'Net sales decreased to EUR 91.6 mn from EUR 109mn in the corresponding period in 2005 .',
  "The brokerage said 2006 has seen a ` true turning point ' in European steel base prices , with better pricing seen carrying through the second quarter of 2006 .",
  'rosendal at outotec.com Eila Paatela , Vice President - Corporate Communications tel. +358 20 529 2004 , +358 400 817198 e-mail eila .',
  "Last week , the Finnish metals and technology group announced plans to sell more than 80 percent of its technology unit to further the company 's strategic goal of becoming the world 's largest stainless steel maker .",
  'Olvi has posted a strong set of figures for the first six months of this year .',
  'Pretax profit jumped to EUR 21.9 million from EUR 3.1 million .',
  'The Finnish national carrier said net loss in April through June was euro26 million , down from a net profit of euro13 million a year earlier .',
  'Shares of Nokia Corp. rose Thursday after the cell phone maker said its third-quarter earnings almost doubled and its share of the global handset market increased .',
  'However , the proportion of the paid standing orders grew in 2009 .',
  'Net profit was 35.5 mln compared with 29.8 mln .',
  'A meeting of Glisten shareholders to vote on the bid will be held on 12 March .',
  'Additionally , information on business segments , competitors and future outlook are provided .',
  "The company 's board of directors will propose a dividend of EUR 0.95 per share for 2008 at the annual general meeting , scheduled to be held on March 23 , 2009 .",
  'Related links : Flexiblebaseloadoperation TheWartsila32generating set Gasconversions This is the shorter of two versions of this press release .',
  'The closing of the transaction is scheduled to take place on January 10 , 2008 .',
  'Honkarakenne also decided yesterday to sell 88,500 of its B-series shares to key staff members for EUR 2.90 per share .',
  'Operating profit rose to EUR 5mn from EUR 2.8 mn in the fourth quarter of 2008 .',
  'The first group of customers to be trained will be paint-shop owners and their assistants .',
  "`` Directors and shareholders alike should ask why these practices were allowed to continue . ''",
  'Lieksaare Oy has earlier been regarded under the control of Saarelainen Oy and the individual shareholders under the shareholder agreement .',
  '`` Our customer has been satisfied with Basware Invoice Automation solution and extends the implementation to new geographies .',
  'Meanwhile , Alfa owns 25.1 % of MegaFon through Altimo , and 4.99 % of Turkcell via an 18.5 % stake in Cukurova Holding .',
  "All YIT Capital Markets Day materials will be available on the company 's Internet site at www.yitgroup.com/investors at 10:30 on September 26 .",
  'Sales of mid-strength beer decreased by 40 % .',
  "What would you like to see changed on Nokia 's next attempt ?",
  'Saunalahti is a part of the Elisa group .',
  'M. and a Master of Business Administration MBA .',
  'At the same time profit of the company increased by 10 % in H1 and reached Ls 79,000 .',
  'This resulted in improved sales figures in Sweden .',
  "- UPM-Kymmene upgraded to ` in-line ' from ` underperform ' by Goldman Sachs .",
  'Increase in the number of shares is based on the option rights which were granted to the management of the company under the stock option plan 2006 .',
  "LCS 's services cover the whole life cycle of software and information systems , from process modelling and tailored software development , to hosting services , solution management , maintenance and support .",
  'Finnish broadband data communication systems provider Teleste Oyj HEL : TLT1V said yesterday it returned to a net profit of EUR 2.7 million USD 3.8 m for the first nine months of 2010 versus a net loss of EUR 579,000 for the same period of 2009 .',
  'The company , which has EUR2 .8 bn in assets , counts among its five largest shareholders Finnish insurers Ilmarinen 4.34 % and Varma 0.70 % , as well as the Finnish state pension fund VER 0.61 % .',
  'Upon completion of the sale Proha would get some USD12 .7 m for its stake in Artemis .',
  'It estimates the operating profit to further improve from the third quarter .',
  'Diluted earnings per share ( EPS ) stood at EUR 0.25 versus EUR 0.42 .',
  "Kone 's net sales rose by some 14 % year-on-year in the first nine months of 2008 .",
  "Subscribers of China Unicom , the nation 's second largest mobile phone operator after China Mobile , are expected to release pictures , videos and blog on the Internet via mobile phones as of March 2008 .",
  "The composite body is coated with a hard coating layer produced by thermal spraying , and the coating is ground . ''",
  'Motorola accounted for 11.5 percent of the South Korean handset market as of the end of April , Samsung held 55 percent and LG Electronics 19 percent , according to Korea-based ATLAS Research Group .',
  'Operating profit rose to EUR 26.7 mn from EUR 14.9 mn in the corresponding period in 2006 .',

In [82]:

# tokenizer(fse)
with torch.no_grad():
        new_outputs = reloaded_lora(**)

with torch.no_grad():
        old_model_outputs = model(**ds)

new_outputs, old_model_outputs

TypeError: PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): BertForSequenceClassification(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30522, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (activation): Tanh()
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
    )
  )
) argument after ** must be a mapping, not Dataset

In [71]:
torch.argmax(new_outputs.logits, dim=-1), torch.argmax(old_model_outputs.logits, dim=-1)

(tensor([1, 1, 0, 1], device='mps:0'), tensor([1, 1, 0, 1], device='mps:0'))

In [68]:
new_outputs.logits.exp()

tensor([[1.6629e-02, 3.7769e+01],
        [4.5750e-03, 1.0514e+02],
        [2.7091e+01, 6.0916e-02],
        [8.1168e-03, 5.1564e+01]], device='mps:0')

In [ ]:
torch.argmax(new_outputs.logits, dim=-1)

tensor([1, 1, 1], device='mps:0')

In [96]:
# tokenized_dataset['train']['input_ids']


training_args = TrainingArguments(
    output_dir='./peft_train',          # Output directory
    eval_strategy="epoch",     # Evaluation strategy to adopt during training
    learning_rate=learning_rate,              # Learning rate for training
    per_device_train_batch_size=batch_size,   # Batch size for training
    per_device_eval_batch_size=batch_size,    # Batch size for evaluation
    num_train_epochs=2,               # Total number of training epochs
    weight_decay=0.20,                # Strength of weight decay
    use_mps_device  = True
)

In [230]:
trainer = Trainer(
    model=lora_model,                         # The instantiated 🤗 Transformers model to be trained
    args=training_args,                  # Training arguments, defined above
    train_dataset=train_dataloader.dataset,
    eval_dataset=eval_dataloader.dataset, # Evaluation dataset
    # compute_metrics=compute_metrics
)

In [231]:
trainer.train()

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 227) + inhomogeneous part.

In [25]:


optimizer = AdamW(model.parameters(), lr = learning_rate)


device = torch.device("cuda" if torch.cuda.is_available() else 'mps' if torch.mps.is_available() else  "cpu")
# print("Device: %s" % device)
# model.to(device)

train_dataloader = DataLoader()

import tqdm
for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for step, batch in enumerate(tqdm.tqdm(dataset['train'])):
        tokenized_batch = tokenizer(batch['text'], padding="max_length", truncation=True, return_tensors='pt')
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        total_loss += loss.detach().float()
        loss.backward()
        optimizer.step()
        # lr_scheduler.step()
        optimizer.zero_grad()

    model.eval()
    eval_loss = 0
    eval_preds = []
    for step, batch in enumerate(tqdm.tqdm(dataset['validation'])):
        batch = {k: v.to(device) for k, v in batch.items()}
        with torch.no_grad():
            outputs = model(**batch)
        loss = outputs.loss
        eval_loss += loss.detach().float()
        eval_preds.extend(
            tokenizer.batch_decode(torch.argmax(outputs.logits, -1).detach().cpu().numpy(), skip_special_tokens=True)
        )

/Users/danielfrimer/Projects/Udacity GenAI/udacity_genai/.venv/lib/python3.12/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|          | 0/43410 [00:00<?, ?it/s]

  0%|          | 0/43410 [00:00<?, ?it/s]

AttributeError: 'str' object has no attribute 'to'

In [41]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
)